### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [sakamoto-kohei-44/Fat-Recipe#154]
MVPリリースお疲れ様でした。
印象としては綺麗に作られていると思いました。
下記に提案を記載しました。ご確認の上、Issue化をお願いいたします。
Issue化が終わりましたら、こちらのissueはcloseしていただいて大丈夫です。
closeの際に作成したissueの完了スケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

## READMEから課題解決する実装がされているか&動いている
こちら確認しました。LGTMです。

## より良いサービスのための提案
- ヘッダーがボタンと被ってしまう箇所があるため、被らないように修正するもしくは菅野講師のPWAに関する過去イベントを参考にして対応を行いましょう。
- ボタン配置：やや端によりすぎていたりして、スマホの際に押しづらさを感じてしまう可能性があるため微調整しましょう。
- AIレシピの結果部分：朝食の表示部分がレシピになっていないので確認して修正しましょう。
- PRCIPES：必要な１日カロリーはDASHBOARDに表示されているものが自動で入っていると、確認のためにページを行き来したりせずに済み、ユーザー体験をよりよくすると思います。
- AIレシピ：結果が表示されるまでの間、アニメーションなどを挟むなどして待機しているユーザーを不安にさせない、別ページへの操作を留まらせる工夫を挟むとユーザー体験もよりよくなると思います。
- SEARCH：検索結果の文字列も翻訳してあげるとより良いと思います。また、クリックした際にエラーになってしまうので、クリックした際にどういった食事なのかを画像とレシピで想像できるようにしてあげると良いと思います。また、ページ遷移ではなく、クリックするとモーダルでそれらが見れるようにする形にすると、ブラウザバック等を挟まず、色々な検索結果を見れるので検討してみてください。（英語のままはやめましょう）
- アプリケーション配下に使用していないファイル等があるように見受けられるので整理しましょう。
- バックエンドのコードに関してはRubocopを通して指摘箇所を修正しましょう。

---

(思いつきのアイディアですが、LINE通知を使って朝・昼・晩のオススメレシピ(AI)を通知してくれる機能とか追加機能の案としてどうかと思いました。)

**Comment by sakamoto-kohei-44** [comment]
レビューありがとうございます！
より良いサービスのための提案や実際に使ってくれた方の意見を参考にし修正していきたいと思います。
issueの完了スケジュールは仕事もあるので長めに十日後の12/17としようと思います。
本リリースに関しては一ヶ月後の1月上旬を目指します。
LINE通知の件も余裕があれば実装する方向で考えようと思います！ありがとうございます。
